# Copyright (c) 2026 IAR Systems AB
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_BLINK=y
CONFIG_BUTTON=y

# IAR Compiler Debug optimizations
CONFIG_DEBUG_OPTIMIZATIONS=y

# Console
CONFIG_CONSOLE=y
CONFIG_SEMIHOST=y
CONFIG_SEMIHOST_CONSOLE=y
CONFIG_UART_CONSOLE=n

# IAR C-SPY RTOS Awareness plugin for Zephyr
CONFIG_TRACING=y
CONFIG_DEBUG_THREAD_INFO=y
# Mutexes and Semaphores
CONFIG_TRACING_OBJECT_TRACKING=y
